Added Python 3.5 and removed 3.4
Conda in TravisCI was unable to create the env using Python 3.4.
Error was:
conda install --yes python=$PYTHON_VERSION --file requirements.txt
Solving environment: failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.4
  - urllib3 -> ipaddress -> python[version='>=2.7,<2.8.0a0'] -> readline=7
  - urllib3 -> ipaddress -> python[version='>=2.7,<2.8.0a0'] -> tk=8.6